apiVersion: v1
kind: Namespace
metadata:
  name: postgresql
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-app
  namespace: postgresql
  annotations:
    atum.dev/stateful-digest: ${ATUM_STATEFUL_DIGEST}
type: kubernetes.io/basic-auth
stringData:
  username: gitlab
  password: ${ATUM_STATEFUL_POSTGRESQL_PASSWORD}
---
apiVersion: v1
kind: Secret
metadata:
  name: atum-platform-stateful-values
  namespace: bigbang
  labels:
    reconcile.fluxcd.io/watch: Enabled
  annotations:
    atum.dev/stateful-digest: ${ATUM_STATEFUL_DIGEST}
type: Opaque
stringData:
  garage-admin-token: ${ATUM_STATEFUL_GARAGE_ADMIN_TOKEN}
  garage-access-key-id: ${ATUM_STATEFUL_GARAGE_ACCESS_KEY_ID}
  garage-secret-access-key: ${ATUM_STATEFUL_GARAGE_SECRET_ACCESS_KEY}
  values.yaml: |
    addons:
      gitlab:
        database:
          password: ${ATUM_STATEFUL_POSTGRESQL_PASSWORD}
        redis:
          password: ${ATUM_STATEFUL_REDIS_PASSWORD}
        objectStorage:
          accessKey: ${ATUM_STATEFUL_GARAGE_ACCESS_KEY_ID}
          accessSecret: ${ATUM_STATEFUL_GARAGE_SECRET_ACCESS_KEY}
        railsSecret: |
          production:
            secret_key_base: ${ATUM_STATEFUL_GITLAB_SECRET_KEY_BASE}
            otp_key_base: ${ATUM_STATEFUL_GITLAB_OTP_KEY_BASE}
            db_key_base: ${ATUM_STATEFUL_GITLAB_DB_KEY_BASE}
            encrypted_settings_key_base: ${ATUM_STATEFUL_GITLAB_ENCRYPTED_SETTINGS_KEY_BASE}
            active_record_encryption_primary_key:
              - ${ATUM_STATEFUL_GITLAB_ACTIVE_RECORD_PRIMARY_KEY}
            active_record_encryption_deterministic_key:
              - ${ATUM_STATEFUL_GITLAB_ACTIVE_RECORD_DETERMINISTIC_KEY}
            active_record_encryption_key_derivation_salt: ${ATUM_STATEFUL_GITLAB_ACTIVE_RECORD_SALT}
            openid_connect_signing_key: "${ATUM_STATEFUL_GITLAB_OPENID_CONNECT_SIGNING_KEY}"
    packages:
      redis:
        values:
          upstream:
            auth:
              password: ${ATUM_STATEFUL_REDIS_PASSWORD}
