addons:
    authservice:
        helmRepo:
            chartName: authservice
            repoName: atum
            tag: 1.1.5-bb.7
        sourceType: helmRepo
        values:
            image:
                repository: 10.77.0.9:32443/atum/authservice
                tag: 1.1.5
    gitlab:
        helmRepo:
            chartName: gitlab
            repoName: atum
            tag: 10.2.4-bb.0
        sourceType: helmRepo
        values:
            global:
                certificates:
                    image:
                        repository: 10.77.0.9:32443/atum/certificates
                        tag: v19.2.4
                gitlabBase:
                    image:
                        repository: 10.77.0.9:32443/atum/gitlab-base
                        tag: v19.2.4
                kubectl:
                    image:
                        repository: 10.77.0.9:32443/atum/gitlab-kubectl
                        tag: v19.2.4
            upstream:
                gitlab:
                    gitaly:
                        image:
                            repository: 10.77.0.9:32443/atum/gitaly
                            tag: v19.2.4
                    gitlab-exporter:
                        image:
                            repository: 10.77.0.9:32443/atum/gitlab-exporter
                            tag: 16.9.0
                    gitlab-shell:
                        image:
                            repository: 10.77.0.9:32443/atum/gitlab-shell
                            tag: v14.56.1
                    migrations:
                        image:
                            repository: 10.77.0.9:32443/atum/gitlab-toolbox
                            tag: v19.2.4
                    praefect:
                        image:
                            repository: 10.77.0.9:32443/atum/gitaly
                            tag: v19.2.4
                    sidekiq:
                        image:
                            repository: 10.77.0.9:32443/atum/gitlab-sidekiq
                            tag: v19.2.4
                    toolbox:
                        image:
                            repository: 10.77.0.9:32443/atum/gitlab-toolbox
                            tag: v19.2.4
                    webservice:
                        image:
                            repository: 10.77.0.9:32443/atum/gitlab-webservice
                            tag: v19.2.4
                        workhorse:
                            image: 10.77.0.9:32443/atum/gitlab-workhorse
                            tag: v19.2.4
                registry:
                    image:
                        repository: 10.77.0.9:32443/atum/gitlab-container-registry
                        tag: v4.40.2-gitlab
                shared-secrets:
                    selfsign:
                        image:
                            repository: 10.77.0.9:32443/atum/cfssl-self-sign
                            tag: v19.2.4
                upgradeCheck:
                    image:
                        repository: 10.77.0.9:32443/atum/ubi9
                        tag: "9.8"
    harbor:
        helmRepo:
            chartName: harbor
            repoName: atum
            tag: 1.19.2-bb.0
        sourceType: helmRepo
        values:
            postgresql:
                image:
                    registry: 10.77.0.9:32443
                    repository: atum/postgresql-18
                    tag: build-8cb4713919ab9f5683cc2904d81267d2bf45e14026473bbdb095e811a7dab154
            redis-bb:
                upstream:
                    image:
                        registry: 10.77.0.9:32443
                        repository: atum/redis-8-10-0
                        tag: 8.10.0
            upstream:
                core:
                    image:
                        repository: 10.77.0.9:32443/atum/harbor-harbor-core
                        tag: v2.15.2
                exporter:
                    image:
                        repository: 10.77.0.9:32443/atum/harbor-harbor-exporter
                        tag: v2.15.2
                jobservice:
                    image:
                        repository: 10.77.0.9:32443/atum/harbor-harbor-jobservice
                        tag: v2.15.2
                portal:
                    image:
                        repository: 10.77.0.9:32443/atum/harbor-harbor-portal
                        tag: v2.15.2
                registry:
                    controller:
                        image:
                            repository: 10.77.0.9:32443/atum/harbor-harbor-registryctl
                            tag: v2.15.2
                    registry:
                        image:
                            repository: 10.77.0.9:32443/atum/harbor-registry
                            tag: v2.15.2
                trivy:
                    image:
                        repository: 10.77.0.9:32443/atum/harbor-trivy-adapter
                        tag: v2.15.2
    headlamp:
        helmRepo:
            chartName: headlamp
            repoName: atum
            tag: 0.44.0-bb.0
        sourceType: helmRepo
        values:
            upstream:
                image:
                    registry: 10.77.0.9:32443
                    repository: atum/headlamp
                    tag: v0.44.0
    keycloak:
        helmRepo:
            chartName: keycloak
            repoName: atum
            tag: 7.3.0-bb.0
        sourceType: helmRepo
        values:
            postgresql:
                image:
                    registry: 10.77.0.9:32443
                    repository: atum/postgresql-18
                    tag: build-8cb4713919ab9f5683cc2904d81267d2bf45e14026473bbdb095e811a7dab154
            upstream:
                image:
                    repository: 10.77.0.9:32443/atum/keycloak
                    tag: 26.7.2
    metricsServer:
        helmRepo:
            chartName: metrics-server
            repoName: atum
            tag: 3.13.1-bb.1
        sourceType: helmRepo
        values:
            upstream:
                image:
                    repository: 10.77.0.9:32443/atum/metrics-server
                    tag: v0.8.1
    vault:
        helmRepo:
            chartName: vault
            repoName: atum
            tag: 0.34.0-bb.0
        sourceType: helmRepo
        values:
            upstream:
                injector:
                    agentImage:
                        repository: 10.77.0.9:32443/atum/vault
                        tag: build-69011978ed52c751d01084bf9bd16cf7003c5956d399086c37037313d982217e
                    image:
                        repository: 10.77.0.9:32443/atum/vault-k8s
                        tag: 1.7.5
                server:
                    image:
                        repository: 10.77.0.9:32443/atum/vault
                        tag: build-69011978ed52c751d01084bf9bd16cf7003c5956d399086c37037313d982217e
fluentbit:
    helmRepo:
        chartName: fluentbit
        repoName: atum
        tag: 0.57.9-bb.0
    sourceType: helmRepo
    values:
        upstream:
            image:
                repository: 10.77.0.9:32443/atum/fluent-bit
                tag: 5.0.9
grafana:
    helmRepo:
        chartName: grafana
        repoName: atum
        tag: 10.5.15-bb.6
    sourceType: helmRepo
    values:
        global:
            imageRegistry: 10.77.0.9:32443
        upstream:
            image:
                registry: 10.77.0.9:32443
                repository: atum/grafana-plugins
                tag: build-985c4e8cc57969dcdca762e470ca2232ae733edc20bd911aefa2c36115e47690
            sidecar:
                image:
                    registry: 10.77.0.9:32443
                    repository: atum/k8s-sidecar
                    tag: 2.8.1
helmRepositories:
    - name: atum
      password: ""
      repository: oci://10.77.0.9:32443/charts
      type: oci
      username: ""
istioCRDs:
    helmRepo:
        chartName: istio-crds
        repoName: atum
        tag: 1.30.3-bb.0
    sourceType: helmRepo
istioGateway:
    helmRepo:
        chartName: gateway
        repoName: atum
        tag: 1.30.3-bb.0
    sourceType: helmRepo
istiod:
    helmRepo:
        chartName: istiod
        repoName: atum
        tag: 1.30.3-bb.0
    sourceType: helmRepo
    values:
        upstream:
            global:
                hub: 10.77.0.9:32443/atum
                tag: 1.30.3
kiali:
    helmRepo:
        chartName: kiali
        repoName: atum
        tag: 2.30.0-bb.0
    sourceType: helmRepo
    values:
        upstream:
            cr:
                spec:
                    deployment:
                        image_name: 10.77.0.9:32443/atum/kiali:v2.30.0
            image:
                repo: 10.77.0.9:32443/atum/kiali-operator
                tag: v2.30.0
kyverno:
    helmRepo:
        chartName: kyverno
        repoName: atum
        tag: 3.8.2-bb.2
    sourceType: helmRepo
    values:
        global:
            image:
                registry: 10.77.0.9:32443
        upstream:
            admissionController:
                container:
                    image:
                        defaultRegistry: 10.77.0.9:32443
                        repository: atum/kyverno-admission-controller
                        tag: v1.18.2
                initContainer:
                    image:
                        defaultRegistry: 10.77.0.9:32443
                        repository: atum/kyverno-preflight
                        tag: v1.18.2
            backgroundController:
                image:
                    defaultRegistry: 10.77.0.9:32443
                    repository: atum/kyverno-background-controller
                    tag: v1.18.2
            cleanupController:
                image:
                    defaultRegistry: 10.77.0.9:32443
                    repository: atum/kyverno-cleanup-controller
                    tag: v1.18.2
            crds:
                migration:
                    image:
                        defaultRegistry: 10.77.0.9:32443
                        repository: atum/kyverno-cli
                        tag: v1.18.2
            global:
                extraEnvVars:
                    - name: KUBE_FEATURE_WatchListClient
                      value: "false"
            reportsController:
                image:
                    defaultRegistry: 10.77.0.9:32443
                    repository: atum/kyverno-reports-controller
                    tag: v1.18.2
            webhooksCleanup:
                image:
                    registry: 10.77.0.9:32443
                    repository: atum/kyverno-readiness-checker
                    tag: v1.18.2
kyvernoPolicies:
    helmRepo:
        chartName: kyverno-policies
        repoName: atum
        tag: 3.3.4-bb.87
    sourceType: helmRepo
kyvernoReporter:
    helmRepo:
        chartName: kyverno-reporter
        repoName: atum
        tag: 3.9.0-bb.1
    sourceType: helmRepo
    values:
        upstream:
            image:
                registry: 10.77.0.9:32443
                repository: atum/policy-reporter
                tag: 3.9.0
            plugin:
                kyverno:
                    image:
                        registry: 10.77.0.9:32443
                        repository: atum/policy-reporter-kyverno-plugin
                        tag: 0.6.2
            ui:
                image:
                    registry: 10.77.0.9:32443
                    repository: atum/policy-reporter-ui
                    tag: 2.7.1
monitoring:
    helmRepo:
        chartName: monitoring
        repoName: atum
        tag: 88.3.0-bb.0
    sourceType: helmRepo
    values:
        upstream:
            alertmanager:
                alertmanagerSpec:
                    image:
                        registry: 10.77.0.9:32443
                        repository: atum/alertmanager
                        tag: v0.33.1
            kube-state-metrics:
                image:
                    registry: 10.77.0.9:32443
                    repository: atum/kube-state-metrics
                    tag: v2.19.1
            prometheus:
                prometheusSpec:
                    image:
                        registry: 10.77.0.9:32443
                        repository: atum/prometheus
                        tag: v3.13.2
            prometheus-node-exporter:
                image:
                    registry: 10.77.0.9:32443
                    repository: atum/node-exporter
                    tag: v1.12.1
            prometheusOperator:
                admissionWebhooks:
                    patch:
                        image:
                            registry: 10.77.0.9:32443
                            repository: atum/kube-webhook-certgen
                            tag: v1.6.9
                image:
                    registry: 10.77.0.9:32443
                    repository: atum/prometheus-operator
                    tag: v0.93.1
                prometheusConfigReloader:
                    image:
                        registry: 10.77.0.9:32443
                        repository: atum/prometheus-config-reloader
                        tag: v0.93.1
                thanosImage:
                    registry: 10.77.0.9:32443
                    repository: atum/thanos
                    tag: v0.42.4
offline: true
packages:
    cert-manager:
        bbCommonValues: false
        enabled: true
        helmRepo:
            chartName: cert-manager
            repoName: atum
            tag: v1.21.1
        istio:
            injection: disabled
        namespace:
            name: cert-manager
        sourceType: helmRepo
        values:
            acmesolver:
                image:
                    repository: 10.77.0.9:32443/atum/cert-manager-acmesolver
                    tag: v1.21.1
            cainjector:
                image:
                    repository: 10.77.0.9:32443/atum/cert-manager-cainjector
                    tag: v1.21.1
            crds:
                enabled: true
            image:
                repository: 10.77.0.9:32443/atum/cert-manager-controller
                tag: v1.21.1
            startupapicheck:
                image:
                    repository: 10.77.0.9:32443/atum/cert-manager-startupapicheck
                    tag: v1.21.1
            webhook:
                image:
                    repository: 10.77.0.9:32443/atum/cert-manager-webhook
                    tag: v1.21.1
    cloudnative-pg:
        helmRepo:
            chartName: cloudnative-pg
            repoName: atum
            tag: 0.29.0-bb.0
        sourceType: helmRepo
        values:
            upstream:
                image:
                    repository: 10.77.0.9:32443/atum/cloudnative-pg
                    tag: 1.30.0
    garage:
        helmRepo:
            chartName: garage
            repoName: atum
            tag: 0.9.3-bb.2
        sourceType: helmRepo
        values:
            garageInit:
                image:
                    repository: 10.77.0.9:32443/atum/garage-init-helper
                    tag: build-e40a8e88b621ba0d530729388c327d479bccc2f74525bd57c0e1ba036279566a
            upstream:
                image:
                    repository: 10.77.0.9:32443/atum/garage
                    tag: v2.3.0
                initImage:
                    repository: 10.77.0.9:32443/atum/busybox
                    tag: 1.37.0
    opensearch:
        helmRepo:
            chartName: opensearch
            repoName: atum
            tag: 3.8.0
        sourceType: helmRepo
        values:
            image:
                repository: 10.77.0.9:32443/atum/opensearch
                tag: 3.8.0
    opensearch-dashboards:
        helmRepo:
            chartName: opensearch-dashboards
            repoName: atum
            tag: 3.8.0
        sourceType: helmRepo
        values:
            image:
                repository: 10.77.0.9:32443/atum/opensearch-dashboards
                tag: 3.8.0
    postgresql:
        helmRepo:
            chartName: cluster
            repoName: atum
            tag: 0.8.1
        sourceType: helmRepo
        values:
            cluster:
                imageName: 10.77.0.9:32443/atum/postgresql-17:17
    redis:
        helmRepo:
            chartName: redis
            repoName: atum
            tag: 27.0.14-bb.0
        sourceType: helmRepo
        values:
            upstream:
                commonConfiguration: |-
                    loadmodule /usr/local/lib/redis/modules/redisearch.so
                    loadmodule /usr/local/lib/redis/modules/redisbloom.so
                    loadmodule /usr/local/lib/redis/modules/redistimeseries.so
                    loadmodule /usr/local/lib/redis/modules/rejson.so
                image:
                    registry: 10.77.0.9:32443
                    repository: atum/redis-8-8-0
                    tag: 8.8.0
prometheusOperatorCRDs:
    helmRepo:
        chartName: prometheus-operator-crds
        repoName: atum
        tag: 31.0.1-bb.0
    sourceType: helmRepo
tempo:
    helmRepo:
        chartName: tempo
        repoName: atum
        tag: 2.1.0-bb.2
    sourceType: helmRepo
    values:
        upstream:
            tempo:
                registry: 10.77.0.9:32443
                repository: atum/tempo
                tag: 2.10.5
wrapper:
    helmRepo:
        chartName: wrapper
        repoName: atum
        tag: 0.4.15
    sourceType: helmRepo
