addons:
    authservice:
        git:
            branch: main
            commit: 5fd08540ea1b83d1e697e2f5507b6f04c5cc5c53
            path: chart
            repo: http://10.77.0.9:3000/atum-upstreams/authservice.git
            semver: 1.1.5-bb.7
            tag: ""
        values:
            image:
                repository: 10.77.0.9:32443/atum/authservice
                tag: 1.1.5
    gitlab:
        git:
            branch: main
            commit: f8e82e63650b1783f720fb868eb9ade4f0df3eb3
            path: chart
            repo: http://10.77.0.9:3000/atum-upstreams/gitlab.git
            semver: 10.2.4-bb.0
            tag: ""
        values:
            global:
                certificates:
                    image:
                        repository: 10.77.0.9:32443/atum/certificates
                        tag: v19.2.4
                gitlabBase:
                    image:
                        repository: 10.77.0.9:32443/atum/gitlab-base
                        tag: v19.2.4
                kubectl:
                    image:
                        repository: 10.77.0.9:32443/atum/gitlab-kubectl
                        tag: v19.2.4
            upstream:
                gitlab:
                    gitaly:
                        image:
                            repository: 10.77.0.9:32443/atum/gitaly
                            tag: v19.2.4
                    gitlab-exporter:
                        image:
                            repository: 10.77.0.9:32443/atum/gitlab-exporter
                            tag: 16.9.0
                    gitlab-shell:
                        image:
                            repository: 10.77.0.9:32443/atum/gitlab-shell
                            tag: v14.56.1
                    migrations:
                        image:
                            repository: 10.77.0.9:32443/atum/gitlab-toolbox
                            tag: v19.2.4
                    praefect:
                        image:
                            repository: 10.77.0.9:32443/atum/gitaly
                            tag: v19.2.4
                    sidekiq:
                        image:
                            repository: 10.77.0.9:32443/atum/gitlab-sidekiq
                            tag: v19.2.4
                    toolbox:
                        image:
                            repository: 10.77.0.9:32443/atum/gitlab-toolbox
                            tag: v19.2.4
                    webservice:
                        image:
                            repository: 10.77.0.9:32443/atum/gitlab-webservice
                            tag: v19.2.4
                        workhorse:
                            image: 10.77.0.9:32443/atum/gitlab-workhorse
                            tag: v19.2.4
                registry:
                    image:
                        repository: 10.77.0.9:32443/atum/gitlab-container-registry
                        tag: v4.40.2-gitlab
                shared-secrets:
                    selfsign:
                        image:
                            repository: 10.77.0.9:32443/atum/cfssl-self-sign
                            tag: v19.2.4
    harbor:
        git:
            branch: main
            commit: d9c43a3ee00b593f308939d6730be8d73773f54f
            path: chart
            repo: http://10.77.0.9:3000/atum-upstreams/harbor.git
            semver: 1.19.2-bb.0
            tag: ""
        values:
            postgresql:
                image:
                    registry: 10.77.0.9:32443
                    repository: atum/postgresql-18
                    tag: "18.4"
            redis-bb:
                upstream:
                    image:
                        registry: 10.77.0.9:32443
                        repository: atum/redis-8-10-0
                        tag: 8.10.0
            upstream:
                core:
                    image:
                        repository: 10.77.0.9:32443/atum/harbor-harbor-core
                        tag: v2.15.2
                exporter:
                    image:
                        repository: 10.77.0.9:32443/atum/harbor-harbor-exporter
                        tag: v2.15.2
                jobservice:
                    image:
                        repository: 10.77.0.9:32443/atum/harbor-harbor-jobservice
                        tag: v2.15.2
                portal:
                    image:
                        repository: 10.77.0.9:32443/atum/harbor-harbor-portal
                        tag: v2.15.2
                registry:
                    controller:
                        image:
                            repository: 10.77.0.9:32443/atum/harbor-harbor-registryctl
                            tag: v2.15.2
                    registry:
                        image:
                            repository: 10.77.0.9:32443/atum/harbor-registry
                            tag: v2.15.2
                trivy:
                    image:
                        repository: 10.77.0.9:32443/atum/harbor-trivy-adapter
                        tag: v2.15.2
    headlamp:
        git:
            branch: main
            commit: bdee331b4cba0ddece5b9b2e2b5b72a32f6e5ebd
            path: chart
            repo: http://10.77.0.9:3000/atum-upstreams/headlamp.git
            semver: 0.44.0-bb.0
            tag: ""
        values:
            upstream:
                image:
                    registry: 10.77.0.9:32443
                    repository: atum/headlamp
                    tag: v0.44.0
            waitJob:
                image: 10.77.0.9:32443/atum/kubectl:v1.35.4
    keycloak:
        git:
            branch: main
            commit: 63f3f02f4b5d32f970bb9d4525331cc8e96cd832
            path: chart
            repo: http://10.77.0.9:3000/atum-upstreams/keycloak.git
            semver: 7.2.2-bb.1
            tag: ""
        values:
            postgresql:
                image:
                    registry: 10.77.0.9:32443
                    repository: atum/postgresql-18
                    tag: "18.4"
            upstream:
                image:
                    repository: 10.77.0.9:32443/atum/keycloak
                    tag: 26.7.0
    metricsServer:
        git:
            branch: main
            commit: ac71d009703207024e92f30bb5e38eba7b45043d
            path: chart
            repo: http://10.77.0.9:3000/atum-upstreams/metrics-server.git
            semver: 3.13.1-bb.1
            tag: ""
        values:
            upstream:
                image:
                    repository: 10.77.0.9:32443/atum/metrics-server
                    tag: v0.8.1
    vault:
        git:
            branch: main
            commit: 51721eb137561b518f22cba0e2e28a7610c03043
            path: chart
            repo: http://10.77.0.9:3000/atum-upstreams/vault.git
            semver: 0.34.0-bb.0
            tag: ""
        values:
            upstream:
                injector:
                    agentImage:
                        repository: 10.77.0.9:32443/atum/vault
                        tag: 1.21.4
                    image:
                        repository: 10.77.0.9:32443/atum/vault-k8s
                        tag: 1.7.5
                server:
                    image:
                        repository: 10.77.0.9:32443/atum/vault
                        tag: 1.21.4
fluentbit:
    git:
        branch: main
        commit: c85d4ca665b9a59645c68f1246ff653d68e5d82b
        path: chart
        repo: http://10.77.0.9:3000/atum-upstreams/fluentbit.git
        semver: 0.57.9-bb.0
        tag: ""
    values:
        upstream:
            image:
                repository: 10.77.0.9:32443/atum/fluent-bit
                tag: 5.0.9
grafana:
    git:
        branch: main
        commit: 70293e4da4fbbfda8ee8676ca70cce67f1b8b381
        path: chart
        repo: http://10.77.0.9:3000/atum-upstreams/grafana.git
        semver: 10.5.15-bb.6
        tag: ""
    values:
        global:
            imageRegistry: 10.77.0.9:32443
        upstream:
            image:
                registry: 10.77.0.9:32443
                repository: atum/grafana-plugins
                tag: 13.0.1
            sidecar:
                image:
                    registry: 10.77.0.9:32443
                    repository: atum/k8s-sidecar
                    tag: 2.8.1
istioCRDs:
    git:
        branch: main
        commit: bf478aca88cbeaaa9a6b74579d339333e0e17bb6
        path: chart
        repo: http://10.77.0.9:3000/atum-upstreams/istio-crds.git
        semver: 1.30.3-bb.0
        tag: ""
istioGateway:
    git:
        branch: main
        commit: 4e0520ebbed7b8be114602a8f7e9993b4a75a9b2
        path: chart
        repo: http://10.77.0.9:3000/atum-upstreams/istio-gateway.git
        semver: 1.30.3-bb.0
        tag: ""
    values:
        gateways:
            passthrough:
                waitJob:
                    image: 10.77.0.9:32443/atum/kubectl:v1.35.4
            public:
                waitJob:
                    image: 10.77.0.9:32443/atum/kubectl:v1.35.4
istiod:
    git:
        branch: main
        commit: 31fe272d29c84e3c88b586891bde1e00322090a9
        path: chart
        repo: http://10.77.0.9:3000/atum-upstreams/istiod.git
        semver: 1.30.3-bb.0
        tag: ""
    values:
        upstream:
            global:
                hub: 10.77.0.9:32443/atum
                tag: 1.30.3
kiali:
    git:
        branch: main
        commit: 1febcc0edd7d866441674625e8eb69d1c01ed4dc
        path: chart
        repo: http://10.77.0.9:3000/atum-upstreams/kiali.git
        semver: 2.30.0-bb.0
        tag: ""
    values:
        upstream:
            cr:
                spec:
                    deployment:
                        image_name: 10.77.0.9:32443/atum/kiali:v2.30.0
            image:
                repo: 10.77.0.9:32443/atum/kiali-operator
                tag: v2.30.0
        waitJob:
            image: 10.77.0.9:32443/atum/kubectl-helper-1-35-7:v1.35.7
kyverno:
    git:
        branch: main
        commit: bef758d5cb05fd4d9a65785354395ed424d5fe3a
        path: chart
        repo: http://10.77.0.9:3000/atum-upstreams/kyverno.git
        semver: 3.8.2-bb.2
        tag: ""
    values:
        global:
            image:
                registry: 10.77.0.9:32443
        upstream:
            admissionController:
                container:
                    image:
                        defaultRegistry: 10.77.0.9:32443
                        repository: atum/kyverno-admission-controller
                        tag: v1.18.2
                initContainer:
                    image:
                        defaultRegistry: 10.77.0.9:32443
                        repository: atum/kyverno-preflight
                        tag: v1.18.2
            backgroundController:
                image:
                    defaultRegistry: 10.77.0.9:32443
                    repository: atum/kyverno-background-controller
                    tag: v1.18.2
            cleanupController:
                image:
                    defaultRegistry: 10.77.0.9:32443
                    repository: atum/kyverno-cleanup-controller
                    tag: v1.18.2
            reportsController:
                image:
                    defaultRegistry: 10.77.0.9:32443
                    repository: atum/kyverno-reports-controller
                    tag: v1.18.2
kyvernoPolicies:
    git:
        branch: main
        commit: 4a5b32d4b3dda100b661ca04a9f4608705c9224e
        path: chart
        repo: http://10.77.0.9:3000/atum-upstreams/kyverno-policies.git
        semver: 3.3.4-bb.87
        tag: ""
    values:
        waitJob:
            image: 10.77.0.9:32443/atum/kubectl-helper-1-34-11:v1.34.11
kyvernoReporter:
    git:
        branch: main
        commit: 9f0d6c810035b09b8e232c305a1ca413ff354347
        path: chart
        repo: http://10.77.0.9:3000/atum-upstreams/kyverno-reporter.git
        semver: 3.9.0-bb.1
        tag: ""
    values:
        upstream:
            image:
                registry: 10.77.0.9:32443
                repository: atum/policy-reporter
                tag: 3.9.0
            plugin:
                kyverno:
                    image:
                        registry: 10.77.0.9:32443
                        repository: atum/policy-reporter-kyverno-plugin
                        tag: 0.6.2
            ui:
                image:
                    registry: 10.77.0.9:32443
                    repository: atum/policy-reporter-ui
                    tag: 2.7.1
monitoring:
    git:
        branch: main
        commit: f6c4fad5f5a89f2b33c5fdadc557f7f7a8d3117a
        path: chart
        repo: http://10.77.0.9:3000/atum-upstreams/monitoring.git
        semver: 88.3.0-bb.0
        tag: ""
    values:
        upstream:
            alertmanager:
                alertmanagerSpec:
                    image:
                        registry: 10.77.0.9:32443
                        repository: atum/alertmanager
                        tag: v0.33.1
            kube-state-metrics:
                image:
                    registry: 10.77.0.9:32443
                    repository: atum/kube-state-metrics
                    tag: v2.19.1
            prometheus:
                prometheusSpec:
                    image:
                        registry: 10.77.0.9:32443
                        repository: atum/prometheus
                        tag: v3.13.2
            prometheus-node-exporter:
                image:
                    registry: 10.77.0.9:32443
                    repository: atum/node-exporter
                    tag: v1.12.1
            prometheusOperator:
                admissionWebhooks:
                    patch:
                        image:
                            registry: 10.77.0.9:32443
                            repository: atum/kube-webhook-certgen
                            tag: v1.6.9
                image:
                    registry: 10.77.0.9:32443
                    repository: atum/prometheus-operator
                    tag: v0.93.1
                prometheusConfigReloader:
                    image:
                        registry: 10.77.0.9:32443
                        repository: atum/prometheus-config-reloader
                        tag: v0.93.1
                thanosImage:
                    registry: 10.77.0.9:32443
                    repository: atum/thanos
                    tag: v0.42.4
packages:
    cloudnative-pg:
        git:
            branch: main
            commit: 8067614001663dba175f5d229c9e6bb5cb23ccf8
            path: chart
            repo: http://10.77.0.9:3000/atum-upstreams/cloudnative-pg.git
            semver: 0.29.0-bb.0
            tag: ""
        values:
            upstream:
                image:
                    repository: 10.77.0.9:32443/atum/cloudnative-pg
                    tag: 1.30.0
    garage:
        git:
            branch: main
            commit: fb39e54e3d4d4263161e53e78f209739346882b2
            path: chart
            repo: http://10.77.0.9:3000/atum-upstreams/garage.git
            semver: 0.9.3-bb.2
            tag: ""
        values:
            garageInit:
                image:
                    repository: 10.77.0.9:32443/atum/garage-init-helper
                    tag: 2.1.0
            upstream:
                image:
                    repository: 10.77.0.9:32443/atum/garage
                    tag: v2.3.0
                initImage:
                    repository: 10.77.0.9:32443/atum/busybox
                    tag: 1.37.0
    opensearch:
        helmRepo:
            tag: 3.8.0
        values:
            image:
                repository: 10.77.0.9:32443/atum/opensearch
                tag: 3.8.0
    opensearch-dashboards:
        helmRepo:
            tag: 3.8.0
        values:
            image:
                repository: 10.77.0.9:32443/atum/opensearch-dashboards
                tag: 3.8.0
    opensearch-operator:
        helmRepo:
            tag: 2.8.2
        values:
            manager:
                image:
                    repository: 10.77.0.9:32443/atum/opensearch-operator
                    tag: 2.8.0
    postgresql:
        git:
            branch: main
            commit: e5fd7c192b39d7d03d7183c73784cc27f1f0bc79
            path: charts/cluster
            repo: http://10.77.0.9:3000/atum-upstreams/postgresql.git
            semver: cluster-v0.8.1
            tag: ""
        values:
            cluster:
                imageName: 10.77.0.9:32443/atum/postgresql-17:17
    redis:
        git:
            branch: main
            commit: ce97559691d4b493a44c7f95b5f04f0a19fdebbd
            path: chart
            repo: http://10.77.0.9:3000/atum-upstreams/redis.git
            semver: 27.0.14-bb.0
            tag: ""
        values:
            upstream:
                image:
                    registry: 10.77.0.9:32443
                    repository: atum/redis-8-8-0
                    tag: 8.8.0
prometheusOperatorCRDs:
    git:
        branch: main
        commit: f595b0e3a23e7558895796d9ec810aa7ca3400fa
        path: chart
        repo: http://10.77.0.9:3000/atum-upstreams/prometheus-operator-crds.git
        semver: 31.0.1-bb.0
        tag: ""
tempo:
    git:
        branch: main
        commit: 00e3261d933da31330be94e44a36c19dafaaa865
        path: chart
        repo: http://10.77.0.9:3000/atum-upstreams/tempo.git
        semver: 2.1.0-bb.2
        tag: ""
    values:
        upstream:
            tempo:
                registry: 10.77.0.9:32443
                repository: atum/tempo
                tag: 2.10.5
wrapper:
    git:
        branch: main
        commit: 86b9ecc74169cb4f9635e7a5ed695014390e9efc
        path: chart
        repo: http://10.77.0.9:3000/atum-upstreams/wrapper.git
        semver: 0.4.15
        tag: ""
    sourceType: git
