apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: bigbang
    namespace: bigbang
spec:
    chartRef:
        kind: OCIRepository
        name: bigbang
        namespace: bigbang
    driftDetection:
        ignore:
            - paths:
                - /data/secrets.yml
              target:
                kind: Secret
                name: gitlab-rails-secret-bb
                namespace: gitlab
        mode: enabled
    install:
        crds: CreateReplace
        disableWait: true
        strategy:
            name: RetryOnFailure
            retryInterval: 5m
    interval: 10m
    postRenderers:
        - kustomize:
            patches:
                - patch: |
                    - op: add
                      path: /spec/insecure
                      value: true
                  target:
                    group: source.toolkit.fluxcd.io
                    kind: HelmRepository
                    name: atum
                    version: v1
    releaseName: bigbang
    targetNamespace: bigbang
    timeout: 30m
    upgrade:
        crds: CreateReplace
        disableWait: true
        strategy:
            name: RetryOnFailure
            retryInterval: 5m
    valuesFrom:
        - kind: ConfigMap
          name: bigbang-operational-values
          valuesKey: values.yaml
        - kind: ConfigMap
          name: bigbang-generated-values
          valuesKey: values.yaml
        - kind: ConfigMap
          name: bigbang-target-values
          valuesKey: values.yaml
        - kind: Secret
          name: atum-platform-stateful-values
          valuesKey: values.yaml
        - kind: Secret
          name: atum-platform-stateful-values
          targetPath: packages.garage.values.garageInit.adminToken
          valuesKey: garage-admin-token
        - kind: Secret
          name: atum-platform-stateful-values
          targetPath: packages.garage.values.upstream.environment[0].value
          valuesKey: garage-admin-token
        - kind: Secret
          name: atum-platform-stateful-values
          targetPath: packages.garage.values.garageInit.consumers[0].credentials.accessKeyId
          valuesKey: garage-access-key-id
        - kind: Secret
          name: atum-platform-stateful-values
          targetPath: packages.garage.values.garageInit.consumers[0].credentials.secretAccessKey
          valuesKey: garage-secret-access-key
        - kind: Secret
          name: atum-platform-identity-values
          optional: true
          valuesKey: values.yaml
        - kind: Secret
          name: atum-sso-ca
          optional: true
          targetPath: sso.certificateAuthority.cert
          valuesKey: ca.crt
