apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
    name: bigbang
    namespace: bigbang
spec:
    insecure: true
    interval: 10m
    layerSelector:
        mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
        operation: copy
    provider: generic
    ref:
        tag: 3.31.1-atum.c4157b10605569ee
    url: oci://10.77.0.9:32443/charts/bigbang
