apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
    name: bigbang
    namespace: bigbang
spec:
    interval: 10m
    ref:
        commit: 5a6955fe38f6e7506c49208f629c3979d5aa424c
        tag: 3.31.0
    timeout: 5m
    url: http://10.77.0.9:3000/atum-upstreams/bigbang.git
