package update

import (
	"errors"
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"atum/cli/config"
)

const finalPackagesPath = "platform/docs/finalpackages.md"

type chartDocumentation struct {
	function string
	project  string
}

func renderFinalPackages(
	desired config.Document,
	lock config.Lock,
	resolvedPackages []resolvedPackage,
	resolvedCharts []resolvedTrackedChart,
	resolvedBootstrap []resolvedBootstrapChart,
) ([]byte, error) {
	target, exists := desired.ActiveTarget()
	if !exists || target.PlatformProfile != "local" {
		return nil, fmt.Errorf("final package snapshot requires the supported local profile")
	}
	packageDocumentation, err := packageDocumentationByID(resolvedPackages)
	if err != nil {
		return nil, err
	}
	chartDocumentation, err := trackedChartDocumentationByID(resolvedCharts)
	if err != nil {
		return nil, err
	}
	bootstrapDocumentation, err := bootstrapChartDocumentationByID(resolvedBootstrap)
	if err != nil {
		return nil, err
	}
	lockedImages := make(map[string]config.LockedImage, len(lock.Delivery.Images))
	for _, image := range lock.Delivery.Images {
		if _, duplicate := lockedImages[image.ID]; duplicate {
			return nil, fmt.Errorf("final package snapshot has duplicate locked image %s", image.ID)
		}
		lockedImages[image.ID] = image
	}
	cnpgOperator, operatorLock, err := currentDirectMirror(
		desired.Delivery.Images,
		lockedImages,
		"package/cloudnative-pg",
		"ghcr.io/cloudnative-pg/cloudnative-pg",
	)
	if err != nil {
		return nil, fmt.Errorf("CloudNativePG operator snapshot: %w", err)
	}
	cnpgOperand, operandLock, err := currentDirectMirror(
		desired.Delivery.Images,
		lockedImages,
		"package/postgresql",
		"ghcr.io/cloudnative-pg/postgresql",
	)
	if err != nil {
		return nil, fmt.Errorf("CloudNativePG operand snapshot: %w", err)
	}

	var document strings.Builder
	document.WriteString(`# Final Package Snapshot

> Generated by ` + "`atum pull updates`" + `. Do not edit this file or use it
> as package-selection input.

## State ownership

- ` + "`atum.json`" + ` supplies human site intent and the updater's replaceable
  selected projections.
- The updater observes the exact selected Big Bang and chart renders.
- ` + "`atum.lock.json`" + ` is the sole immutable resolution record.
- The immutable publication receipt lives only in ignored
  ` + "`.atum/state/publication.lock.json`" + `.
- This file is a generated human-readable projection of those current facts;
  it owns no selection or runtime state.

Big Bang package repositories are authoritative chart inputs. Registry1/Iron
Bank coordinates exposed by the selected charts are non-fetchable comparison
evidence only: Atum never fetches, mirrors, builds from, or deploys them. Every
delivered image comes from an immutable official upstream input, either as a
direct mirror or as material for one evidence-backed compatibility build.

## Selected platform

| Component | Version | Immutable source |
| --- | --- | --- |
`)
	writeMarkdownRow(&document, "Big Bang", desired.Platform.BigBang.Version,
		desired.Platform.BigBang.URL+" @ "+desired.Platform.BigBang.Commit)
	targetRelease, err := desired.Orchestration.TargetRelease()
	if err != nil {
		return nil, err
	}
	writeMarkdownRow(&document, "Kubernetes", targetRelease.Kubernetes,
		targetRelease.Kubespray.URL+" @ "+targetRelease.Kubespray.Commit)
	writeMarkdownRow(&document, "Flux", desired.Platform.Flux.Version,
		desired.Platform.Flux.URL+" @ "+desired.Platform.Flux.Commit)

	document.WriteString(`
## Kubespray selected-runtime inventories

Each row describes the exact files and images selected from the pinned
Kubespray downloads map for the canonical local all-in-one topology. Disabled
CNIs, runtimes, cloud providers, and addons are not delivery obligations.

| Kubernetes | Kubespray commit | Selection input SHA-256 | Selected inventory SHA-256 | File count | Image count | Inventory scope |
| --- | --- | --- | --- | --- | --- | --- |
`)
	kubesprayRows, err := renderKubesprayInventoryRows(
		desired.Delivery.Kubespray,
	)
	if err != nil {
		return nil, err
	}
	document.Write(kubesprayRows)

	document.WriteString(`
## Big Bang and generic packages

The function and project columns come from each exact selected chart's
` + "`Chart.yaml`" + ` metadata; Atum does not maintain a package-description
catalog.

| Selected chart function | Package | Integration | Version | License evidence | Authoritative chart input | Chart project/source metadata |
| --- | --- | --- | --- | --- | --- | --- |
`)
	packages := append([]config.Package(nil), desired.Platform.Packages...)
	sort.Slice(packages, func(i, j int) bool { return packages[i].ID < packages[j].ID })
	for _, pkg := range packages {
		fact, found := packageDocumentation[pkg.ID]
		if !found {
			return nil, fmt.Errorf("final package snapshot has no selected chart metadata for %s", pkg.ID)
		}
		writeMarkdownRow(
			&document,
			fact.function,
			pkg.ID,
			pkg.Integration,
			pkg.Source.Version,
			pkg.License,
			pkg.Source.URL+" @ "+pkg.Source.Commit+" / "+pkg.RepositoryChartPath(),
			fact.project,
		)
	}

	document.WriteString(`
The selected CloudNativePG package renders the operator from ` +
		"`" + cnpgOperator.Delivery.Default.Source + "`" + ` (` + "`" + cnpgOperator.ID + "`" + `),
locked at ` + "`" + operatorLock.Delivery.Digest + "`" + `. The official
` + "`cloudnative-pg/charts`" + ` ` + "`charts/cluster`" + ` chart renders its
operand from ` + "`" + cnpgOperand.Delivery.Default.Source + "`" + ` (` + "`" + cnpgOperand.ID + "`" + `),
locked at ` + "`" + operandLock.Delivery.Digest + "`" + `. Both are direct
immutable mirrors; the CloudNativePG operand has no Atum wrapper or
compatibility build. PostgreSQL images rendered by other selected subcharts
are independent obligations and appear below with their own current evidence.

## Independently selected application charts

| Selected chart function | Chart | Version | App version | License | Official chart archive | Chart project/source metadata |
| --- | --- | --- | --- | --- | --- | --- |
`)
	charts := append([]config.TrackedChart(nil), desired.Platform.Charts...)
	sort.Slice(charts, func(i, j int) bool { return charts[i].ID < charts[j].ID })
	for _, chart := range charts {
		fact, found := chartDocumentation[chart.ID]
		if !found {
			return nil, fmt.Errorf("final package snapshot has no selected chart metadata for %s", chart.ID)
		}
		writeMarkdownRow(
			&document,
			fact.function,
			chart.Name,
			chart.Version,
			chart.AppVersion,
			chart.License,
			chart.Source.URL+" # sha256:"+chart.ArchiveSHA256,
			fact.project,
		)
	}

	document.WriteString(`
The selected Big Bang shared wrapper chart remains only for generic
OpenSearch releases that explicitly request it. Atum does not use the wrapper
as a workload coordinator.

## Bootstrap charts

| Selected chart function | Chart | Version | App version | License | Official chart source | Chart project/source metadata |
| --- | --- | --- | --- | --- | --- | --- |
`)
	bootstrap := append([]config.Chart(nil), desired.ActiveBootstrapCharts()...)
	sort.Slice(bootstrap, func(i, j int) bool { return bootstrap[i].ID < bootstrap[j].ID })
	for _, chart := range bootstrap {
		fact, found := bootstrapDocumentation[chart.ID]
		if !found {
			return nil, fmt.Errorf("final package snapshot has no selected bootstrap chart metadata for %s", chart.ID)
		}
		writeMarkdownRow(
			&document,
			fact.function,
			chart.Name,
			chart.Version,
			chart.AppVersion,
			chart.License,
			chart.Source.URL+" # sha256:"+chart.ArchiveSHA256,
			fact.project,
		)
	}

	document.WriteString(`
## Runtime and helper image delivery

| ID | Version | License | Official provenance | Final internal target | Decision | Official immutable input |
| --- | --- | --- | --- | --- | --- | --- |
`)
	images := append([]config.Image(nil), desired.Delivery.Images...)
	sort.Slice(images, func(i, j int) bool { return images[i].ID < images[j].ID })
	for _, image := range images {
		choice := image.Delivery.Default
		locked, found := lockedImages[image.ID]
		if !found {
			return nil, fmt.Errorf("final package snapshot image %s has no lock entry", image.ID)
		}
		var decision, input string
		switch choice.Type {
		case "mirror":
			if locked.Delivery.Digest == "" {
				return nil, fmt.Errorf("direct mirror %s has no immutable digest", image.ID)
			}
			decision = "direct immutable mirror"
			input = choice.Source + " @ " + locked.Delivery.Digest
		case "build":
			if image.Discovery == "first-party" {
				if image.Compatibility != nil {
					return nil, fmt.Errorf(
						"first-party build %s carries compatibility evidence",
						image.ID,
					)
				}
				decision = "reproducible first-party build: " +
					choice.BakeTarget
			} else {
				if image.Compatibility == nil ||
					strings.TrimSpace(image.Compatibility.Incompatibility) == "" ||
					strings.TrimSpace(image.Compatibility.RemovalCondition) == "" ||
					len(image.Compatibility.Observations) == 0 {
					return nil, fmt.Errorf("compatibility build %s has no current rendered evidence", image.ID)
				}
				decision = "evidence-backed compatibility build: " + choice.BakeTarget
			}
			input = strings.Join(choice.Materials, "<br>")
		default:
			return nil, fmt.Errorf("image %s has unsupported delivery type %q", image.ID, choice.Type)
		}
		writeMarkdownRow(
			&document,
			image.ID,
			image.Version,
			image.License,
			image.Provenance,
			image.Target,
			decision,
			input,
		)
	}

	document.WriteString(`
## Retained compatibility builds

Only compatibility builds appear below; reproducible first-party builds appear
in the preceding delivery table. Each reason and render-evidence record comes
from the final selected candidate render.
Registry1 values in the last column are non-fetchable comparison evidence,
never build inputs.

| ID | Consumers | Current incompatibility | Removal condition | Final rendered evidence | Pinned build inputs | Non-fetchable comparison evidence |
| --- | --- | --- | --- | --- | --- | --- |
`)
	retainedBuildRows, err := renderRetainedCompatibilityBuildRows(images)
	if err != nil {
		return nil, err
	}
	document.Write(retainedBuildRows)
	document.WriteString(`
Build output digests are publication facts and therefore never enter the root
lock. The immutable publication receipt is written only to ignored
` + "`.atum/state/publication.lock.json`" + `; this snapshot does not
claim an output that has not been produced.
`)
	return []byte(document.String()), nil
}

func renderKubesprayInventoryRows(
	inventories []config.KubesprayArtifactInventory,
) ([]byte, error) {
	var rows strings.Builder
	for _, inventory := range inventories {
		if inventory.InventoryScope != config.KubespraySelectedRuntimeInventory ||
			!validHexSHA256(inventory.SelectionInputSHA256) ||
			!validHexSHA256(inventory.SelectedInventorySHA256) ||
			len(inventory.Files) == 0 ||
			len(inventory.Images) == 0 {
			return nil, fmt.Errorf(
				"Kubespray %s package snapshot lacks selected-runtime provenance",
				inventory.KubernetesVersion,
			)
		}
		writeMarkdownRow(
			&rows,
			inventory.KubernetesVersion,
			inventory.KubesprayCommit,
			inventory.SelectionInputSHA256,
			inventory.SelectedInventorySHA256,
			fmt.Sprintf("%d", len(inventory.Files)),
			fmt.Sprintf("%d", len(inventory.Images)),
			inventory.InventoryScope,
		)
	}
	return []byte(rows.String()), nil
}

func renderRetainedCompatibilityBuildRows(images []config.Image) ([]byte, error) {
	var rows strings.Builder
	buildCount := 0
	for _, image := range images {
		if image.Delivery.Default.Type != "build" ||
			image.Discovery == "first-party" {
			continue
		}
		if image.Compatibility == nil ||
			strings.TrimSpace(image.Compatibility.RemovalCondition) == "" {
			return nil, fmt.Errorf(
				"compatibility build %s has no removal condition",
				image.ID,
			)
		}
		buildCount++
		writeMarkdownRow(
			&rows,
			image.ID,
			strings.Join(image.Consumers, "<br>"),
			image.Compatibility.Incompatibility,
			image.Compatibility.RemovalCondition,
			renderedEvidence(image.Compatibility.Observations),
			strings.Join(image.Delivery.Default.Materials, "<br>"),
			strings.Join(image.BigBangRefs, "<br>"),
		)
	}
	if buildCount == 0 {
		rows.WriteString("| None | — | — | — | — | — | — |\n")
	}
	return []byte(rows.String()), nil
}

func packageDocumentationByID(
	packages []resolvedPackage,
) (map[string]chartDocumentation, error) {
	result := make(map[string]chartDocumentation, len(packages))
	for _, resolved := range packages {
		if _, duplicate := result[resolved.Package.ID]; duplicate {
			return nil, fmt.Errorf("duplicate resolved package %s", resolved.Package.ID)
		}
		fact, err := readChartDocumentation(
			filepath.Join(
				resolved.Checkout,
				filepath.FromSlash(resolved.Package.RepositoryChartPath()),
			),
			resolved.Package.Source.URL,
		)
		if err != nil {
			return nil, fmt.Errorf("read package %s documentation: %w", resolved.Package.ID, err)
		}
		result[resolved.Package.ID] = fact
	}
	return result, nil
}

func trackedChartDocumentationByID(
	charts []resolvedTrackedChart,
) (map[string]chartDocumentation, error) {
	result := make(map[string]chartDocumentation, len(charts))
	for _, resolved := range charts {
		if _, duplicate := result[resolved.Chart.ID]; duplicate {
			return nil, fmt.Errorf("duplicate resolved chart %s", resolved.Chart.ID)
		}
		fact, err := readChartDocumentation(
			resolved.ArchivePath,
			resolved.Chart.Source.URL,
		)
		if err != nil {
			return nil, fmt.Errorf("read chart %s documentation: %w", resolved.Chart.ID, err)
		}
		result[resolved.Chart.ID] = fact
	}
	return result, nil
}

func bootstrapChartDocumentationByID(
	charts []resolvedBootstrapChart,
) (map[string]chartDocumentation, error) {
	result := make(map[string]chartDocumentation, len(charts))
	for _, resolved := range charts {
		if _, duplicate := result[resolved.Chart.ID]; duplicate {
			return nil, fmt.Errorf("duplicate resolved bootstrap chart %s", resolved.Chart.ID)
		}
		fact, err := readChartDocumentation(
			resolved.ArchivePath,
			resolved.Chart.Source.URL,
		)
		if err != nil {
			return nil, fmt.Errorf("read bootstrap chart %s documentation: %w", resolved.Chart.ID, err)
		}
		result[resolved.Chart.ID] = fact
	}
	return result, nil
}

func readChartDocumentation(path, fallbackProject string) (chartDocumentation, error) {
	metadata, err := readChartMetadata(path)
	if err != nil {
		return chartDocumentation{}, err
	}
	function := strings.TrimSpace(metadata.Description)
	if function == "" {
		function = strings.TrimSpace(metadata.Name)
	}
	project := strings.TrimSpace(metadata.Home)
	if project == "" {
		for _, source := range metadata.Sources {
			if project = strings.TrimSpace(source); project != "" {
				break
			}
		}
	}
	if project == "" {
		project = strings.TrimSpace(fallbackProject)
	}
	if function == "" || project == "" {
		return chartDocumentation{}, errors.New("selected chart metadata has no function or project reference")
	}
	return chartDocumentation{function: function, project: project}, nil
}

func currentDirectMirror(
	images []config.Image,
	locked map[string]config.LockedImage,
	consumer, officialRepository string,
) (config.Image, config.LockedImage, error) {
	var match config.Image
	found := false
	for _, image := range images {
		choice := image.Delivery.Default
		if choice.Type != "mirror" ||
			imageRepository(choice.Source) != officialRepository ||
			!containsString(image.Consumers, consumer) {
			continue
		}
		if found {
			return config.Image{}, config.LockedImage{}, fmt.Errorf(
				"consumer %s has multiple direct mirrors for %s",
				consumer,
				officialRepository,
			)
		}
		match, found = image, true
	}
	if !found {
		return config.Image{}, config.LockedImage{}, fmt.Errorf(
			"consumer %s has no direct mirror for %s",
			consumer,
			officialRepository,
		)
	}
	resolution, exists := locked[match.ID]
	if !exists || resolution.Delivery.Digest == "" {
		return config.Image{}, config.LockedImage{}, fmt.Errorf(
			"image %s has no immutable lock digest",
			match.ID,
		)
	}
	return match, resolution, nil
}

func renderedEvidence(observations []config.ImageRuntimeEvidence) string {
	values := make([]string, len(observations))
	for index, observation := range observations {
		values[index] = observation.Artifact + " @ " + observation.RenderedLocation +
			" # sha256:" + observation.RuntimeContractSHA256
	}
	return strings.Join(values, "<br>")
}

func writeMarkdownRow(builder *strings.Builder, values ...string) {
	builder.WriteString("|")
	for _, value := range values {
		builder.WriteByte(' ')
		builder.WriteString(markdownCell(value))
		builder.WriteString(" |")
	}
	builder.WriteByte('\n')
}

func markdownCell(value string) string {
	value = strings.ReplaceAll(strings.TrimSpace(value), "|", `\|`)
	value = strings.ReplaceAll(value, "\r", "")
	return strings.ReplaceAll(value, "\n", "<br>")
}
