//go:build !ignore_autogenerated

// Copyright Atum contributors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Administrator) DeepCopyInto(out *Administrator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Administrator.
func (in *Administrator) DeepCopy() *Administrator {
	if in == nil {
		return nil
	}
	out := new(Administrator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupsScope) DeepCopyInto(out *GroupsScope) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupsScope.
func (in *GroupsScope) DeepCopy() *GroupsScope {
	if in == nil {
		return nil
	}
	out := new(GroupsScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakClient) DeepCopyInto(out *KeycloakClient) {
	*out = *in
	if in.RedirectURIs != nil {
		in, out := &in.RedirectURIs, &out.RedirectURIs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WebOrigins != nil {
		in, out := &in.WebOrigins, &out.WebOrigins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakClient.
func (in *KeycloakClient) DeepCopy() *KeycloakClient {
	if in == nil {
		return nil
	}
	out := new(KeycloakClient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakIntent) DeepCopyInto(out *KeycloakIntent) {
	*out = *in
	out.Administrator = in.Administrator
	out.GroupsScope = in.GroupsScope
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Clients != nil {
		in, out := &in.Clients, &out.Clients
		*out = make([]KeycloakClient, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakIntent.
func (in *KeycloakIntent) DeepCopy() *KeycloakIntent {
	if in == nil {
		return nil
	}
	out := new(KeycloakIntent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformIdentityConfiguration) DeepCopyInto(out *PlatformIdentityConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformIdentityConfiguration.
func (in *PlatformIdentityConfiguration) DeepCopy() *PlatformIdentityConfiguration {
	if in == nil {
		return nil
	}
	out := new(PlatformIdentityConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlatformIdentityConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformIdentityConfigurationList) DeepCopyInto(out *PlatformIdentityConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PlatformIdentityConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformIdentityConfigurationList.
func (in *PlatformIdentityConfigurationList) DeepCopy() *PlatformIdentityConfigurationList {
	if in == nil {
		return nil
	}
	out := new(PlatformIdentityConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlatformIdentityConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformIdentityConfigurationSpec) DeepCopyInto(out *PlatformIdentityConfigurationSpec) {
	*out = *in
	in.Keycloak.DeepCopyInto(&out.Keycloak)
	in.Vault.DeepCopyInto(&out.Vault)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformIdentityConfigurationSpec.
func (in *PlatformIdentityConfigurationSpec) DeepCopy() *PlatformIdentityConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(PlatformIdentityConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformIdentityConfigurationStatus) DeepCopyInto(out *PlatformIdentityConfigurationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformIdentityConfigurationStatus.
func (in *PlatformIdentityConfigurationStatus) DeepCopy() *PlatformIdentityConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(PlatformIdentityConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultExternalGroup) DeepCopyInto(out *VaultExternalGroup) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultExternalGroup.
func (in *VaultExternalGroup) DeepCopy() *VaultExternalGroup {
	if in == nil {
		return nil
	}
	out := new(VaultExternalGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultIntent) DeepCopyInto(out *VaultIntent) {
	*out = *in
	out.Policy = in.Policy
	in.Role.DeepCopyInto(&out.Role)
	out.ExternalGroup = in.ExternalGroup
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultIntent.
func (in *VaultIntent) DeepCopy() *VaultIntent {
	if in == nil {
		return nil
	}
	out := new(VaultIntent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultPolicy) DeepCopyInto(out *VaultPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultPolicy.
func (in *VaultPolicy) DeepCopy() *VaultPolicy {
	if in == nil {
		return nil
	}
	out := new(VaultPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultRole) DeepCopyInto(out *VaultRole) {
	*out = *in
	if in.RedirectURIs != nil {
		in, out := &in.RedirectURIs, &out.RedirectURIs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultRole.
func (in *VaultRole) DeepCopy() *VaultRole {
	if in == nil {
		return nil
	}
	out := new(VaultRole)
	in.DeepCopyInto(out)
	return out
}
