// Code generated by controller-gen. DO NOT EDIT.
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *PlatformConfiguration) DeepCopyInto(out *PlatformConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}
func (in *PlatformConfiguration) DeepCopy() *PlatformConfiguration {
	if in == nil { return nil }
	out := new(PlatformConfiguration); in.DeepCopyInto(out); return out
}
func (in *PlatformConfiguration) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *PlatformConfigurationList) DeepCopyInto(out *PlatformConfigurationList) {
	*out = *in; out.TypeMeta = in.TypeMeta; in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]PlatformConfiguration, len(in.Items))
		for i := range in.Items { in.Items[i].DeepCopyInto(&out.Items[i]) }
	}
}
func (in *PlatformConfigurationList) DeepCopy() *PlatformConfigurationList {
	if in == nil { return nil }
	out := new(PlatformConfigurationList); in.DeepCopyInto(out); return out
}
func (in *PlatformConfigurationList) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *PlatformConfigurationSpec) DeepCopyInto(out *PlatformConfigurationSpec) {
	*out = *in
	in.Keycloak.DeepCopyInto(&out.Keycloak)
	in.Vault.DeepCopyInto(&out.Vault)
}
func (in *KeycloakIntent) DeepCopyInto(out *KeycloakIntent) {
	*out = *in
	out.Scopes = append([]string(nil), in.Scopes...)
	if in.Clients != nil {
		out.Clients = make([]KeycloakClient, len(in.Clients))
		for i := range in.Clients {
			out.Clients[i] = in.Clients[i]
			out.Clients[i].RedirectURIs = append([]string(nil), in.Clients[i].RedirectURIs...)
			out.Clients[i].WebOrigins = append([]string(nil), in.Clients[i].WebOrigins...)
		}
	}
}
func (in *VaultIntent) DeepCopyInto(out *VaultIntent) {
	*out = *in
	out.Role = in.Role
	out.Role.RedirectURIs = append([]string(nil), in.Role.RedirectURIs...)
	out.Role.Scopes = append([]string(nil), in.Role.Scopes...)
}
func (in *PlatformConfigurationStatus) DeepCopyInto(out *PlatformConfigurationStatus) {
	*out = *in
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		copy(out.Conditions, in.Conditions)
	}
}
