pid /var/run/nginx.pid;
worker_processes auto;

events {
  worker_connections 1024;
}

http {
  access_log off;
  error_log /dev/stderr warn;
  sendfile on;

  server {
    listen 8080;
    server_name _;
    root /data/current;
    autoindex off;

    location = /healthz {
      default_type text/plain;
      limit_except GET {
        deny all;
      }
      return 200 "ok\n";
    }

    location / {
      limit_except GET {
        deny all;
      }
      try_files $uri =404;
    }
  }
}
