apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - platform-secrets.yaml
  - prep.yaml
  - platform-profile-prep.yaml
  - bigbang.yaml
  - platform-certificates.yaml
  - platform-profile-access.yaml
  - atum-operator.yaml
