apiVersion: v1
kind: ConfigMap
metadata:
  name: atum-identity-contract
  namespace: keycloak
data:
  schemaVersion: atum.dev/identity/v1
  issuer: https://keycloak.atum.test/auth/realms/master
  digest: ${ATUM_IDENTITY_DIGEST}
  clients: 86e15d59c32f8a640a9c5387172a57ac7073836e539df7e94e1b79970b833673
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: atum-identity-contract
  namespace: vault
data:
  schemaVersion: atum.dev/identity/v1
  issuer: https://keycloak.atum.test/auth/realms/master
  digest: ${ATUM_IDENTITY_DIGEST}
  clients: 86e15d59c32f8a640a9c5387172a57ac7073836e539df7e94e1b79970b833673
