apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - public-certificate.yaml
    - keycloak-certificate.yaml
    - harbor-sso-ca.yaml
    - keycloak-sso-ca.yaml
    - vault-sso-ca.yaml
