apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
    name: local-path-provisioner
    namespace: local-path-storage
spec:
    insecure: true
    interval: 30m
    layerSelector:
        mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
        operation: copy
    provider: generic
    ref:
        tag: 0.0.37
    timeout: 60s
    url: oci://10.77.0.9:32443/charts/local-path-provisioner
