health:
    readinessProbe:
        httpGet:
            path: /ready
            port: health
        initialDelaySeconds: 5
        periodSeconds: 5
        timeoutSeconds: 5
helperImage:
    repository: 10.77.0.9:32443/atum/busybox
    tag: 1.37.0-mirror-7a3ebe5bfd1a4a19797d20b0c0bb39d44393e9a03fd852c0
helperPod:
    resources:
        requests:
            cpu: 25m
            memory: 64Mi
image:
    pullPolicy: IfNotPresent
    repository: 10.77.0.9:32443/atum/local-path-provisioner
    tag: v0.0.37-mirror-c3f2c60ee2490eb83ac00101d7e239fd8c20a5b8b4038e2d
nodePathMap:
    - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
      paths:
        - /var/lib/atum/local-path-provisioner
resources:
    requests:
        cpu: 25m
        memory: 64Mi
storageClass:
    create: true
    defaultClass: true
    defaultVolumeType: hostPath
    name: atum-local-path
    provisionerName: atum.dev/local-path
    reclaimPolicy: Retain
    volumeBindingMode: WaitForFirstConsumer
