env:
    cp_enable: "false"
    lb_enable: "false"
    svc_election: "true"
    svc_enable: "true"
    vip_arp: "true"
    vip_interface: ""
    vip_leaderelection: "false"
image:
    pullPolicy: IfNotPresent
    repository: 10.77.0.9:32443/atum/kube-vip
    tag: v1.2.3
resources:
    limits:
        cpu: 200m
        memory: 128Mi
    requests:
        cpu: 25m
        memory: 32Mi
securityContext:
    allowPrivilegeEscalation: false
    capabilities:
        add:
            - NET_ADMIN
            - NET_RAW
        drop:
            - ALL
    privileged: false
    seccompProfile:
        type: RuntimeDefault
