apiVersion: platform.atum.dev/v1alpha1
kind: PlatformIdentityConfiguration
metadata:
  name: atum
  namespace: atum-system
spec:
  domain: atum.test
  keycloak:
    administrator:
      group: atum-admins
      realmRole: admin
      username: atum
    clients:
    - audience: true
      id: atum-headlamp
      kind: PublicPKCE
      redirectURIs:
      - https://headlamp.atum.test/oidc-callback
      webOrigins:
      - https://headlamp.atum.test
    - audience: true
      id: atum-kiali
      kind: Confidential
      redirectURIs:
      - https://kiali.atum.test/kiali
      webOrigins:
      - https://kiali.atum.test
    - id: atum-grafana
      kind: Confidential
      redirectURIs:
      - https://grafana.atum.test/login/generic_oauth
      webOrigins:
      - https://grafana.atum.test
    - id: atum-gitlab
      kind: Confidential
      redirectURIs:
      - https://gitlab.atum.test/users/auth/openid_connect/callback
      webOrigins:
      - https://gitlab.atum.test
    - id: atum-policy-reporter
      kind: Confidential
      redirectURIs:
      - https://policy.atum.test/callback
      webOrigins:
      - https://policy.atum.test
    - id: atum-harbor
      kind: Confidential
      redirectURIs:
      - https://harbor.atum.test/c/oidc/callback
      webOrigins:
      - https://harbor.atum.test
    - id: atum-vault
      kind: Confidential
      redirectURIs:
      - https://vault.atum.test/ui/vault/auth/oidc/oidc/callback
      webOrigins:
      - https://vault.atum.test
    - id: atum-prometheus
      kind: Confidential
      redirectURIs:
      - https://prometheus.atum.test/oauth2/callback
      webOrigins:
      - https://prometheus.atum.test
    - id: atum-alertmanager
      kind: Confidential
      redirectURIs:
      - https://alertmanager.atum.test/oauth2/callback
      webOrigins:
      - https://alertmanager.atum.test
    - id: atum-opensearch
      kind: Confidential
      redirectURIs:
      - https://opensearch.atum.test/oauth2/callback
      webOrigins:
      - https://opensearch.atum.test
    groupsScope:
      claimName: groups
    realm: master
    scopes:
    - openid
    - profile
    - email
    - groups
  vault:
    authPath: oidc
    externalGroup:
      claim: atum-admins
      name: atum-admins
      policyName: atum-admin
    policy:
      name: atum-admin
      purpose: PlatformAdministration
    role:
      clientID: atum-vault
      groupsClaim: groups
      name: atum-admin
      redirectURIs:
      - https://vault.atum.test/ui/vault/auth/oidc/oidc/callback
      scopes:
      - openid
      - profile
      - email
      - groups
status: {}
