apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app.kubernetes.io/name: atum-operator
        app.kubernetes.io/version: 0.1.1
    name: atum-operator
    namespace: atum-system
spec:
    replicas: 1
    selector:
        matchLabels:
            app.kubernetes.io/name: atum-operator
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app.kubernetes.io/name: atum-operator
                app.kubernetes.io/version: 0.1.1
        spec:
            automountServiceAccountToken: false
            containers:
                - image: 10.77.0.9:32443/atum/atum-operator:build-dac2936d25fbf72c010280d05c15532626418b1c840c82e9b1f0da189096332a
                  imagePullPolicy: IfNotPresent
                  livenessProbe:
                    httpGet:
                        path: /healthz
                        port: health
                  name: manager
                  ports:
                    - containerPort: 8081
                      name: health
                  readinessProbe:
                    httpGet:
                        path: /readyz
                        port: health
                  resources:
                    limits:
                        cpu: 250m
                        memory: 128Mi
                    requests:
                        cpu: 25m
                        memory: 48Mi
                  securityContext:
                    allowPrivilegeEscalation: false
                    capabilities:
                        drop:
                            - ALL
                    readOnlyRootFilesystem: true
                    runAsNonRoot: true
                    runAsUser: 65532
                  volumeMounts:
                    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
                      name: kube-api-access
                      readOnly: true
            securityContext:
                runAsNonRoot: true
                seccompProfile:
                    type: RuntimeDefault
            serviceAccountName: atum-operator
            volumes:
                - name: kube-api-access
                  projected:
                    defaultMode: 420
                    sources:
                        - serviceAccountToken:
                            expirationSeconds: 3600
                            path: token
                        - configMap:
                            items:
                                - key: ca.crt
                                  path: ca.crt
                            name: kube-root-ca.crt
                        - downwardAPI:
                            items:
                                - fieldRef:
                                    apiVersion: v1
                                    fieldPath: metadata.namespace
                                  path: namespace
