apiVersion: apps/v1
kind: Deployment
metadata:
  name: atum-operator
  namespace: atum-system
  labels:
    app.kubernetes.io/name: atum-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: atum-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: atum-operator
    spec:
      serviceAccountName: atum-operator
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: manager
          image: 10.77.0.9:32443/atum/atum-operator:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: health
              containerPort: 8081
          livenessProbe:
            httpGet: {path: /healthz, port: health}
          readinessProbe:
            httpGet: {path: /readyz, port: health}
          resources:
            requests: {cpu: 25m, memory: 48Mi}
            limits: {cpu: 250m, memory: 128Mi}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65532
