apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: atum-test-root-ca
  namespace: cert-manager
spec:
  commonName: atum-test
  secretName: atum-test-root-ca
  isCA: true
  duration: 87600h
  renewBefore: 720h
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  usages:
    - cert sign
    - crl sign
    - digital signature
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: atum-test-selfsigned
