containerd_registries_mirrors:
    - mirrors:
        - capabilities:
            - pull
            - resolve
          host: http://10.77.0.9:32443
          skip_verify: true
      prefix: 10.77.0.9:32443
      server: http://10.77.0.9:32443
    - mirrors:
        - capabilities:
            - pull
            - resolve
          host: http://10.77.0.9:32443/atum/kubespray/quay.io
          override_path: true
          skip_verify: true
      prefix: quay.io
      server: http://10.77.0.9:32443/atum/kubespray/quay.io
    - mirrors:
        - capabilities:
            - pull
            - resolve
          host: http://10.77.0.9:32443/atum/kubespray/registry.k8s.io
          override_path: true
          skip_verify: true
      prefix: registry.k8s.io
      server: http://10.77.0.9:32443/atum/kubespray/registry.k8s.io
kube_image_repo: 10.77.0.9:32443/atum/kubespray/registry.k8s.io
kubeadm_image_repo: 10.77.0.9:32443/atum/kubespray/registry.k8s.io
quay_image_repo: 10.77.0.9:32443/atum/kubespray/quay.io
