apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-vip-cloud-provider
  namespace: kube-system
spec:
  releaseName: kube-vip-cloud-provider
  targetNamespace: kube-system
  interval: 10m
  timeout: 10m
  dependsOn:
    - name: kube-vip
      namespace: kube-system
  chartRef:
    kind: OCIRepository
    name: kube-vip-cloud-provider
    namespace: kube-system
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 1m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 1m
  driftDetection:
    mode: enabled
  valuesFrom:
    - kind: ConfigMap
      name: kube-vip-cloud-provider-values
      valuesKey: values.yaml
