apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  releaseName: cert-manager
  targetNamespace: cert-manager
  interval: 10m
  timeout: 10m
  chartRef:
    kind: OCIRepository
    name: cert-manager
    namespace: cert-manager
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 1m
  upgrade:
    crds: CreateReplace
    strategy:
      name: RetryOnFailure
      retryInterval: 1m
  driftDetection:
    mode: enabled
  valuesFrom:
    - kind: ConfigMap
      name: cert-manager-values
      valuesKey: values.yaml
