apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
    name: cert-manager
    namespace: cert-manager
spec:
    insecure: true
    interval: 30m
    layerSelector:
        mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
        operation: copy
    provider: generic
    ref:
        tag: v1.21.1
    timeout: 60s
    url: oci://10.77.0.9:32443/charts/cert-manager
