acmesolver:
    image:
        pullPolicy: IfNotPresent
        repository: 10.77.0.9:32443/atum/cert-manager-acmesolver
        tag: v1.21.1
cainjector:
    image:
        pullPolicy: IfNotPresent
        repository: 10.77.0.9:32443/atum/cert-manager-cainjector
        tag: v1.21.1
    replicaCount: 1
crds:
    enabled: true
    keep: true
image:
    pullPolicy: IfNotPresent
    repository: 10.77.0.9:32443/atum/cert-manager-controller
    tag: v1.21.1
replicaCount: 1
startupapicheck:
    enabled: true
    image:
        pullPolicy: IfNotPresent
        repository: 10.77.0.9:32443/atum/cert-manager-startupapicheck
        tag: v1.21.1
webhook:
    image:
        pullPolicy: IfNotPresent
        repository: 10.77.0.9:32443/atum/cert-manager-webhook
        tag: v1.21.1
    replicaCount: 1
